"""Domain enums for the Telegram OCR processing system."""

from enum import Enum


class UserRole(str, Enum):
    STUDENT = "STUDENT"
    ADMIN = "ADMIN"


class ProcessingStatus(str, Enum):
    RECEIVED = "RECEIVED"
    DOWNLOADING = "DOWNLOADING"
    VALIDATING = "VALIDATING"
    OCR_PROCESSING = "OCR_PROCESSING"
    PARSING = "PARSING"
    QUALITY_CHECK = "QUALITY_CHECK"
    RENDERING = "RENDERING"
    READY = "READY"
    FAILED = "FAILED"


class DeliveryStatus(str, Enum):
    PENDING = "PENDING"
    DELIVERY_SUCCESS = "DELIVERY_SUCCESS"
    DELIVERY_FAILED = "DELIVERY_FAILED"


class ExportStatus(str, Enum):
    PENDING = "PENDING"
    GENERATING = "GENERATING"
    READY = "READY"
    DELIVERING = "DELIVERING"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    SENT = "SENT"
    FAILED = "FAILED"


class ExportFormat(str, Enum):
    DOCX = "DOCX"
    XLSX = "XLSX"
    BOTH = "BOTH"


class ScheduleType(str, Enum):
    DAILY = "DAILY"


class ScheduleStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    DISABLED = "DISABLED"
    ERROR = "ERROR"


class AdminAction(str, Enum):
    ADMIN_LOGIN = "ADMIN_LOGIN"
    ADMIN_PANEL_OPEN = "ADMIN_PANEL_OPEN"
    ADMIN_BLOCK_STUDENT = "ADMIN_BLOCK_STUDENT"
    ADMIN_UNBLOCK_STUDENT = "ADMIN_UNBLOCK_STUDENT"
    ADMIN_CREATE_EXPORT = "ADMIN_CREATE_EXPORT"
    ADMIN_RESEND_EXPORT = "ADMIN_RESEND_EXPORT"
    ADMIN_DELETE_EXPORT = "ADMIN_DELETE_EXPORT"
    ADMIN_ADD_RECIPIENT = "ADMIN_ADD_RECIPIENT"
    ADMIN_EDIT_RECIPIENT = "ADMIN_EDIT_RECIPIENT"
    ADMIN_DISABLE_RECIPIENT = "ADMIN_DISABLE_RECIPIENT"
    ADMIN_ENABLE_RECIPIENT = "ADMIN_ENABLE_RECIPIENT"
    ADMIN_DELETE_RECIPIENT = "ADMIN_DELETE_RECIPIENT"
    ADMIN_CREATE_SCHEDULE = "ADMIN_CREATE_SCHEDULE"
    ADMIN_EDIT_SCHEDULE = "ADMIN_EDIT_SCHEDULE"
    ADMIN_PAUSE_SCHEDULE = "ADMIN_PAUSE_SCHEDULE"
    ADMIN_RESUME_SCHEDULE = "ADMIN_RESUME_SCHEDULE"
    ADMIN_DELETE_SCHEDULE = "ADMIN_DELETE_SCHEDULE"
    ADMIN_DELETE_SUBMISSION = "ADMIN_DELETE_SUBMISSION"
    ADMIN_REPROCESS_SUBMISSION = "ADMIN_REPROCESS_SUBMISSION"
    ADMIN_RESEND_SUBMISSION = "ADMIN_RESEND_SUBMISSION"


class QualityGateResult(str, Enum):
    PASS = "PASS"
    RETRY = "RETRY"
    FAIL = "FAIL"


class OCRProviderType(str, Enum):
    TESSERACT = "tesseract"
    GEMINI = "gemini"
    MOCK = "mock"
