"""initial_postgresql_schema

Revision ID: f0297755bdfd
Revises: 
Create Date: 2026-09-04 18:19:37.042254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0297755bdfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_safe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index('ix_admin_audit_logs_action_created', 'admin_audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_user_id'), 'admin_audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('export_type', sa.String(length=32), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('format', sa.Enum('DOCX', 'XLSX', 'BOTH', name='exportformat'), nullable=False),
    sa.Column('content_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'DELIVERING', 'PARTIAL_SUCCESS', 'SENT', 'FAILED', name='exportstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_date_from'), 'exports', ['date_from'], unique=False)
    op.create_index(op.f('ix_exports_date_to'), 'exports', ['date_to'], unique=False)
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipients_is_active'), 'recipients', ['is_active'], unique=False)
    op.create_index(op.f('ix_recipients_telegram_chat_id'), 'recipients', ['telegram_chat_id'], unique=True)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_type', sa.Enum('DAILY', name='scheduletype'), nullable=False),
    sa.Column('time_of_day', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('format', sa.Enum('DOCX', 'XLSX', 'BOTH', name='exportformat'), nullable=False),
    sa.Column('content_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_is_active'), 'schedules', ['is_active'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_blocked'), 'users', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('export_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('export_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'DELIVERY_SUCCESS', 'DELIVERY_FAILED', name='deliverystatus'), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_recipients_export_id'), 'export_recipients', ['export_id'], unique=False)
    op.create_index(op.f('ix_export_recipients_recipient_id'), 'export_recipients', ['recipient_id'], unique=False)
    op.create_table('schedule_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('export_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'business_date', name='uq_schedule_business_date')
    )
    op.create_index(op.f('ix_schedule_executions_business_date'), 'schedule_executions', ['business_date'], unique=False)
    op.create_index(op.f('ix_schedule_executions_schedule_id'), 'schedule_executions', ['schedule_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('original_file_path', sa.String(length=512), nullable=False),
    sa.Column('processed_file_path', sa.String(length=512), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('option_a', sa.Text(), nullable=True),
    sa.Column('option_b', sa.Text(), nullable=True),
    sa.Column('option_c', sa.Text(), nullable=True),
    sa.Column('option_d', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'DOWNLOADING', 'VALIDATING', 'OCR_PROCESSING', 'PARSING', 'QUALITY_CHECK', 'RENDERING', 'READY', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'DELIVERY_SUCCESS', 'DELIVERY_FAILED', name='deliverystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_business_date'), 'submissions', ['business_date'], unique=False)
    op.create_index('ix_submissions_date_status', 'submissions', ['business_date', 'processing_status'], unique=False)
    op.create_index(op.f('ix_submissions_delivery_status'), 'submissions', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_submissions_job_id'), 'submissions', ['job_id'], unique=True)
    op.create_index(op.f('ix_submissions_processing_status'), 'submissions', ['processing_status'], unique=False)
    op.create_index('ix_submissions_sort', 'submissions', ['submitted_at_utc', 'id'], unique=False)
    op.create_index(op.f('ix_submissions_submitted_at_utc'), 'submissions', ['submitted_at_utc'], unique=False)
    op.create_index('ix_submissions_user_date', 'submissions', ['user_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('processing_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('safe_error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_attempts_submission_id'), 'processing_attempts', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_attempts_submission_id'), table_name='processing_attempts')
    op.drop_table('processing_attempts')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index('ix_submissions_user_date', table_name='submissions')
    op.drop_index(op.f('ix_submissions_submitted_at_utc'), table_name='submissions')
    op.drop_index('ix_submissions_sort', table_name='submissions')
    op.drop_index(op.f('ix_submissions_processing_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_job_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_delivery_status'), table_name='submissions')
    op.drop_index('ix_submissions_date_status', table_name='submissions')
    op.drop_index(op.f('ix_submissions_business_date'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_schedule_executions_schedule_id'), table_name='schedule_executions')
    op.drop_index(op.f('ix_schedule_executions_business_date'), table_name='schedule_executions')
    op.drop_table('schedule_executions')
    op.drop_index(op.f('ix_export_recipients_recipient_id'), table_name='export_recipients')
    op.drop_index(op.f('ix_export_recipients_export_id'), table_name='export_recipients')
    op.drop_table('export_recipients')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_blocked'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_schedules_is_active'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_recipients_telegram_chat_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_is_active'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_index(op.f('ix_exports_date_to'), table_name='exports')
    op.drop_index(op.f('ix_exports_date_from'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_user_id'), table_name='admin_audit_logs')
    op.drop_index('ix_admin_audit_logs_action_created', table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
